In [125]:
import pandas as pd
import json

In [184]:
# python
# @app.route('/names')
#  List of sample names.

def funcsampleName():
    
    df_names= pd.read_csv('DataSets/belly_button_biodiversity_samples.csv')
    nameList = []
    for each_name in df_names.columns[1:]:
        nameList.append(each_name)
   
    return nameList

In [185]:
funcsampleName()

['BB_940',
 'BB_941',
 'BB_943',
 'BB_944',
 'BB_945',
 'BB_946',
 'BB_947',
 'BB_948',
 'BB_949',
 'BB_950',
 'BB_952',
 'BB_953',
 'BB_954',
 'BB_955',
 'BB_956',
 'BB_958',
 'BB_959',
 'BB_960',
 'BB_961',
 'BB_962',
 'BB_963',
 'BB_964',
 'BB_966',
 'BB_967',
 'BB_968',
 'BB_969',
 'BB_970',
 'BB_971',
 'BB_972',
 'BB_973',
 'BB_974',
 'BB_975',
 'BB_978',
 'BB_1233',
 'BB_1234',
 'BB_1235',
 'BB_1236',
 'BB_1237',
 'BB_1238',
 'BB_1242',
 'BB_1243',
 'BB_1246',
 'BB_1253',
 'BB_1254',
 'BB_1258',
 'BB_1259',
 'BB_1260',
 'BB_1264',
 'BB_1265',
 'BB_1273',
 'BB_1275',
 'BB_1276',
 'BB_1277',
 'BB_1278',
 'BB_1279',
 'BB_1280',
 'BB_1281',
 'BB_1282',
 'BB_1283',
 'BB_1284',
 'BB_1285',
 'BB_1286',
 'BB_1287',
 'BB_1288',
 'BB_1289',
 'BB_1290',
 'BB_1291',
 'BB_1292',
 'BB_1293',
 'BB_1294',
 'BB_1295',
 'BB_1296',
 'BB_1297',
 'BB_1298',
 'BB_1308',
 'BB_1309',
 'BB_1310',
 'BB_1374',
 'BB_1415',
 'BB_1439',
 'BB_1441',
 'BB_1443',
 'BB_1486',
 'BB_1487',
 'BB_1489',
 'BB_1490',
 'BB_1491',
 'BB_1494',
 'BB_1495',
 'BB_1497',
 'BB_1499',
 'BB_1500',
 'BB_1501',
 'BB_1502',
 'BB_1503',
 'BB_1504',
 'BB_1505',
 'BB_1506',
 'BB_1507',
 'BB_1508',
 'BB_1510',
 'BB_1511',
 'BB_1512',
 'BB_1513',
 'BB_1514',
 'BB_1515',
 'BB_1516',
 'BB_1517',
 'BB_1518',
 'BB_1519',
 'BB_1521',
 'BB_1524',
 'BB_1526',
 'BB_1527',
 'BB_1530',
 'BB_1531',
 'BB_1532',
 'BB_1533',
 'BB_1534',
 'BB_1535',
 'BB_1536',
 'BB_1537',
 'BB_1539',
 'BB_1540',
 'BB_1541',
 'BB_1542',
 'BB_1543',
 'BB_1544',
 'BB_1545',
 'BB_1546',
 'BB_1547',
 'BB_1548',
 'BB_1549',
 'BB_1550',
 'BB_1551',
 'BB_1552',
 'BB_1553',
 'BB_1554',
 'BB_1555',
 'BB_1556',
 'BB_1557',
 'BB_1558',
 'BB_1561',
 'BB_1562',
 'BB_1563',
 'BB_1564',
 'BB_1572',
 'BB_1573',
 'BB_1574',
 'BB_1576',
 'BB_1577',
 'BB_1581',
 'BB_1601']

In [5]:
# python
# @app.route('/otu')
# List of OTU descriptions.

# Returns a list of OTU descriptions in the following format

def funcOtuDesc():
    df_otuDesc = pd.read_csv("DataSets/belly_button_biodiversity_otu_id.csv")
    otuDescList = []
    for each_otuDesc in df_otuDesc['lowest_taxonomic_unit_found']:
        otuDescList.append(each_otuDesc)
        
    return otuDescList

In [68]:
#python
# @app.route('/metadata/<sample>')
# MetaData for a given sample.

#Args: Sample in the format: `BB_940`

#Returns a json dictionary of sample metadata in the format

def funcSampleMetaData():
    df_sampleMetaData = pd.read_csv("DataSets/Belly_Button_Biodiversity_Metadata.csv")
    df_sampleMetaData["SAMPLEID"]="BB_" + df_sampleMetaData["SAMPLEID"].astype(str)
    df_sampleMetaData = df_sampleMetaData[['AGE','BBTYPE','ETHNICITY','GENDER','LOCATION','SAMPLEID']]
    df_sampleMetaData_JSON = df_sampleMetaData.to_json(orient='records')
    
    return df_sampleMetaData_JSON

In [66]:
df_sampleMetaData = pd.read_csv("DataSets/Belly_Button_Biodiversity_Metadata.csv")

In [70]:
df_sampleMetaData.columns

Index(['SAMPLEID', 'EVENT', 'ETHNICITY', 'GENDER', 'AGE', 'WFREQ', 'BBTYPE',
       'LOCATION', 'COUNTRY012', 'ZIP012', 'COUNTRY1319', 'ZIP1319', 'DOG',
       'CAT', 'IMPSURFACE013', 'NPP013', 'MMAXTEMP013', 'PFC013',
       'IMPSURFACE1319', 'NPP1319', 'MMAXTEMP1319', 'PFC1319'],
      dtype='object')

In [233]:
funcSampleMetaDataWFREQ().head()

   SAMPLEID  WFREQ
0       940    2.0
1       941    1.0
2       943    1.0
3       944    1.0
4       945    1.0

In [93]:
#python
# @app.route('/wfreq/<sample>')
# Weekly Washing Frequency as a number.

# Args: Sample in the format: `BB_940`

# Returns an integer value for the weekly washing frequency `WFREQ`


def funcSampleMetaDataWFREQ():
    df_sampleMetaData = pd.read_csv("DataSets/Belly_Button_Biodiversity_Metadata.csv")
    
    #added BB_ to the column sampleid
    df_sampleMetaData['SAMPLEID'] = "BB_" + df_sampleMetaData["SAMPLEID"].astype(str)
    
    df_sampleMetaDataWFREQ = df_sampleMetaData[['SAMPLEID','WFREQ']]
    
    #filled na values with 0
    df_sampleMetaDataWFREQ = df_sampleMetaDataWFREQ.fillna(0) 
    
    #json weekly frequency dataframe
    df_sampleMetaDataWFREQ = df_sampleMetaDataWFREQ.to_json(orient='records')
    
    
    return df_sampleMetaDataWFREQ

In [241]:
pd.read_csv('DataSets/belly_button_biodiversity_samples.csv').head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [139]:
def samples():
    # data load from csv file - pandas
    biodiversity_samples = pd.read_csv('DataSets/belly_button_biodiversity_samples.csv')
    biodiversity_samples = biodiversity_samples[['otu_id','BB_940']].sort_values('BB_940', ascending=0)
    biodiversity_samples.columns = ['otu_id', "sample_values"]
    biodiversity_samplesL = biodiversity_samples[biodiversity_samples['sample_values'] > 10]
    small_vals = biodiversity_samples[biodiversity_samples['sample_values'] < 10]['sample_values'].sum()
    smallD = {'otu_id' : 'Other GERMS', 'sample_values' : small_vals}
    biodiversity_samplesS = pd.DataFrame(smallD, index=[0])
    df = pd.concat([biodiversity_samplesL, biodiversity_samplesS])

    return df.to_dict('list')

In [142]:
biodiversity_samplesS

NameError: name 'biodiversity_samplesS' is not defined

In [140]:
samples()

{'otu_id': [1167,
  2859,
  482,
  2264,
  41,
  1189,
  352,
  189,
  2318,
  1977,
  3450,
  874,
  1959,
  2191,
  1950,
  2077,
  2275,
  2184,
  944,
  2244,
  2419,
  2024,
  2811,
  2782,
  165,
  2396,
  2247,
  2011,
  'Other GERMS'],
 'sample_values': [163.0,
  126.0,
  113.0,
  78.0,
  71.0,
  51.0,
  50.0,
  47.0,
  40.0,
  40.0,
  37.0,
  36.0,
  30.0,
  28.0,
  25.0,
  23.0,
  22.0,
  19.0,
  19.0,
  14.0,
  13.0,
  13.0,
  13.0,
  12.0,
  12.0,
  11.0,
  11.0,
  11.0,
  279.0]}

In [174]:
df_sortedSampleValues = pd.read_csv('DataSets/belly_button_biodiversity_samples.csv')

In [175]:
df_sortedSampleValues['rowSUM'] = df_sortedSampleValues.iloc[::,1:].sum(axis=1)

ValueError: Boolean array expected for the condition, not float64

In [183]:
df_sortedSampleValues.set_index(['otu_id'])

,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,BB_950,...,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601,rowSUM
otu_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
2,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,4.0
3,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
4,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,60.0
5,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
6,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
7,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
8,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,1,0,0,0,0,0,0,0,2.0
9,0.0,0,0,0,0,1,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
10,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,11.0
11,1.0,0,0,0,0,0,0,1.0,0,0.0,...,0,0,0,0,0,0,0,0,0,10.0
12,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
13,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
14,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
15,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
16,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
17,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
18,0.0,0,0,0,0,2,1,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,5.0
19,1.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
20,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
21,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
22,1.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
23,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
24,1.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,1,0,0,0,0,5.0
25,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
26,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
27,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
28,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
29,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,5.0
30,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3645,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3646,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
3647,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,5.0
3648,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3649,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
3650,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,2.0
3651,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3652,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3653,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3654,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3655,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,1,0,0,0,0,0,0,1.0
3656,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,2.0
3657,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,1,0,0,0,0,0,0,2.0
3658,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3659,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,2,0,0,0,0,0,0,2.0
3660,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,3,0,0,0,0,0,0,92.0
3661,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
3662,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3663,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
3664,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
3665,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
3666,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3667,0.0,0,0,0,0,1,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,2.0
3668,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3669,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,3.0
3670,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,1,0,0,0,1.0
3671,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3672,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,138,0,0,0,139.0
3673,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0
3674,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,1.0

In [179]:
# ```python
# @app.route('/samples/<sample>')
#     """OTU IDs and Sample Values for a given sample.

#     Sort your Pandas DataFrame (OTU ID and Sample Value)
#     in Descending Order by Sample Value

#     Return a list of dictionaries containing sorted lists  for `otu_ids`
#     and `sample_values`


def funcDictSortedSampleValues():
    df_sortedSampleValues = pd.read_csv('DataSets/belly_button_biodiversity_samples.csv')
    df_sortedSampleValues= df.sort_values(by=list(df.columns),ascending=False, axis=0)
    dictSortedSamplesValues = df_sortedSampleValues.to_dict(orient="list")
    return dictSortedSamplesValues

In [185]:
df_sortedSampleValues = pd.read_csv('DataSets/belly_button_biodiversity_samples.csv')
df_sortedSampleValues= df.sort_values(by=list(df.columns),ascending=False, axis=0)
dictSortedSamplesValues = df_sortedSampleValues.to_dict(orient="list")

In [212]:
NewdictSortedSamplesValues = []

# for key,values in dictSortedSamplesValues.items():

In [218]:
pd.read_csv('DataSets/belly_button_biodiversity_samples.csv').head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [219]:
pd.read_sql(sql='select* from samples_metadata;',con=sqlite3.connect("DataSets/belly_button_biodiversity.sqlite")).head()

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852,37.172222,54.5,0.0,1,0.0,33.990002,25.5
1,941,0,Caucasian/Midleastern,F,34,1.0,I,Chicago/IL,0,0,...,0,0,0,0.000000,0.0,0.0,0,0.0,0.000000,0.0
2,943,BellyButtonsScienceOnline,Caucasian,F,49,1.0,I,Omaha/NE,0,0,...,0,0,0,0.000000,0.0,0.0,0,0.0,0.000000,0.0
3,944,BellyButtonsScienceOnline,European,M,44,1.0,I,NewHaven/CT,usa,7079,...,no,yes,0,35.816666,16.0,0.0,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48,1.0,I,Philidelphia/PA,usa,84404,...,no,no,0,37.783333,4.0,0.0,0,5613.0,33.634445,24.0